[package]
name = "ferrum-app-services"
description = "Application use cases for Ferrum API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
ferrum-domain = { path = "../domain" }
ferrum-http-client = { path = "../http-client" }
ferrum-secrets = { path = "../secrets" }
ferrum-storage = { path = "../storage" }
ferrum-variables = { path = "../variables" }
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
uuid.workspace = true

[lints]
workspace = true
